// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestQuest.Context;

namespace TestQuest.Migrations
{
    [DbContext(typeof(TestQuestContext))]
    [Migration("20240308193743_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestQuest.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("TestQuest.Models.Letter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromWhomId")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToWhomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromWhomId");

                    b.HasIndex("ToWhomId");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("TestQuest.Models.Letter", b =>
                {
                    b.HasOne("TestQuest.Models.Employe", "FromWhom")
                        .WithMany()
                        .HasForeignKey("FromWhomId");

                    b.HasOne("TestQuest.Models.Employe", "ToWhom")
                        .WithMany()
                        .HasForeignKey("ToWhomId");

                    b.Navigation("FromWhom");

                    b.Navigation("ToWhom");
                });
#pragma warning restore 612, 618
        }
    }
}
